// Copies contract ABIs and deployed addresses into packages/shared/src/generated.ts.
// Run after `forge build` and after every deployment: `node scripts/export-abi.mjs`.
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const abiOf = (name) => JSON.parse(readFileSync(join(root, `contracts/out/${name}.sol/${name}.json`), "utf8")).abi;

const deployments = {};
const dir = join(root, "contracts/deployments");
if (existsSync(dir)) {
  for (const f of readdirSync(dir).filter((f) => f.endsWith(".json"))) {
    const d = JSON.parse(readFileSync(join(dir, f), "utf8"));
    deployments[d.chainId] = { miners: d.miners, veinFunder: d.veinFunder, startBlock: d.startBlock };
  }
}

const out = `// Generated by scripts/export-abi.mjs. Do not edit.
export const ormineMinersAbi = ${JSON.stringify(abiOf("OrmineMiners"), null, 2)} as const;

export const veinFunderAbi = ${JSON.stringify(abiOf("VeinFunder"), null, 2)} as const;

export const deployments = ${JSON.stringify(deployments, null, 2)} as const;
`;
writeFileSync(join(root, "packages/shared/src/generated.ts"), out);
console.log("generated.ts written; deployments for chains:", Object.keys(deployments).join(", ") || "none");
