// Pixel icons drawn from small character maps (ORMINE_DESIGN.md, appendix A).
// One character = one pixel, "." = transparent. Every icon is our own: no stock OS artwork.

export const PIXEL_PALETTE = {
  k: "#1B1410",
  w: "#FFFFFF",
  g: "#9AA0A6",
  G: "#D7DBDF",
  d: "#C9A43A",
  y: "#F2C94C",
  Y: "#FFE89A",
  r: "#6B4A3A",
  R: "#8A5E49",
  o: "#E98D24",
  O: "#F5CC17",
  L: "#F4F76A",
  b: "#8F4822",
  B: "#B8682F",
  // Extra letters for the app status icons (Done / Failed).
  n: "#2E7D32",
  N: "#6CC24A",
  x: "#B3261E",
  X: "#E5484D",
} as const satisfies Record<string, string>;

const pick = [
  "....kkkkkkk.....",
  "..kkGGGGGGGkk...",
  ".kGGgggggggGGk..",
  "kGgkkkkbkkkkgGk.",
  "kgk....kbk...kgk",
  "kk.....kBk....kk",
  ".......kbk......",
  ".......kBk......",
  ".......kbk......",
  ".......kBk......",
  ".......kbk......",
  ".......kBk......",
  ".......kbk......",
  ".......kBk......",
  ".......kkk......",
  "................",
];

export const PIXEL_MAPS = {
  // ---- appendix A ----
  pick,
  // The big hero cursor: same pickaxe with a lighter handle.
  pickBig: pick.map((row) => row.replace(/b/g, "B")),
  ore: [
    "................",
    "......kkkk......",
    "....kkrrrrkk....",
    "...krrrOOrrrk...",
    "..krrrOLLOrrRk..",
    ".krrrrOOrrrRrrk.",
    ".krRrrrrrrOOrrk.",
    "krrrrrrrrOLLOrrk",
    "krrOOrrrrrOOrRrk",
    "krOLLOrrRrrrrrrk",
    "krrOOrrrrrrrOOrk",
    ".krrrRrrrrrOLOk.",
    "..kkrrrrrrrrrk..",
    "....kkkkkkkkk...",
    "................",
    "................",
  ],
  folder: [
    "................",
    "................",
    ".kkkkkk.........",
    "kyyyyyyk........",
    "kyyyyyyykkkkkkk.",
    "kYYYYYYYYYYYYYyk",
    "kyyyyyyyyyyyyyyk",
    "kyyyyyyyyyyyyyyk",
    "kyyyyyyyyyyyyyyk",
    "kyyyyyyyyyyyyyyk",
    "kyyyyyyyyyyyyyyk",
    "kyyyyyyyyyyyyyyk",
    "kddddddddddddddk",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
  ],
  bin: [
    ".......o........",
    "......oOo..o....",
    ".....oOLOooOo...",
    ".....oOLLOOLo...",
    "...kkkkkkkkkkk..",
    "..kGGGGGGGGGGGk.",
    "...kgggggggggk..",
    "...kgkgkgkgkgk..",
    "...kgkgkgkgkgk..",
    "...kgkgkgkgkgk..",
    "...kgkgkgkgkgk..",
    "...kgkgkgkgkgk..",
    "...kgggggggggk..",
    "....kkkkkkkkk...",
    "................",
    "................",
  ],
  cartmini: [
    "................",
    "....kk..........",
    "...kOOk.kk......",
    "..kOLLOkOOk.....",
    ".kOOOOOOOLOk....",
    "kkkkkkkkkkkkkkk.",
    "kBbbbbbbbbbbbBk.",
    "kbBBBBBBBBBBBbk.",
    "kbbbbbbbbbbbbbk.",
    ".kbbbbbbbbbbbk..",
    "..kkkkkkkkkkk...",
    "..kgk.....kgk...",
    "..kkk.....kkk...",
    "................",
    "................",
    "................",
  ],
  // Upgrade: a gold arrow pointing up.
  up: [
    "................",
    "................",
    ".......kk.......",
    "......kOOk......",
    ".....kOLOOk.....",
    "....kOLOOOOk....",
    "...kOOOOOOOOk...",
    "..kkkkOOOOkkkk..",
    ".....kOOOOk.....",
    ".....kOOOOk.....",
    ".....kOOOOk.....",
    ".....kddddk.....",
    ".....kkkkkk.....",
    "................",
    "................",
    "................",
  ],
  arrow: [
    "k...........",
    "kk..........",
    "kwk.........",
    "kwwk........",
    "kwwwk.......",
    "kwwwwk......",
    "kwwwwwk.....",
    "kwwwwwwk....",
    "kwwwwwwwk...",
    "kwwwwwwwwk..",
    "kwwwwwwwwwk.",
    "kwwwwwwkkkkk",
    "kwwwkwwk....",
    "kwwk.kwwk...",
    "kwk..kwwk...",
    "kk....kwwk..",
    "k.....kwwk..",
    ".......kwwk.",
    ".......kkk..",
  ],

  // ---- app status icons, same grid and outline ----
  done: [
    "................",
    "................",
    "............kkk.",
    "...........kNNk.",
    "..........kNNnk.",
    ".........kNNnk..",
    ".kkk....kNNnk...",
    "kNNNk..kNNnk....",
    "knNNNkkNNnk.....",
    ".knNNNNNnk......",
    "..knNNNnk.......",
    "...knNnk........",
    "....knk.........",
    ".....k..........",
    "................",
    "................",
  ],
  failed: [
    "................",
    "................",
    "..kkk......kkk..",
    ".kXXXk....kXXXk.",
    ".kXXXxk..kXXXxk.",
    "..kXXXxkkXXXxk..",
    "...kXXXxXXXxk...",
    "....kXXXXXxk....",
    "....kXXXXXxk....",
    "...kXXXxXXXxk...",
    "..kXXXxkkXXXxk..",
    ".kXXXxk..kXXXxk.",
    ".kXXxk....kXXxk.",
    "..kkk......kkk..",
    "................",
    "................",
  ],
  warning: [
    "................",
    ".......kk.......",
    "......kYYk......",
    "......kYyk......",
    ".....kYyyyk.....",
    ".....kYkkyk.....",
    "....kYykkyyk....",
    "....kYykkyyk....",
    "...kYyykkyyyk...",
    "...kYyykkyyyk...",
    "..kYyyyyyyyyyk..",
    "..kYyyykkyyyyk..",
    ".kYyyyykkyyyyyk.",
    ".kddddddddddddk.",
    ".kkkkkkkkkkkkkk.",
    "................",
  ],
  // Travel between veins: a two-way arrow.
  move: [
    "................",
    "................",
    "................",
    "................",
    "...k........k...",
    "..kOk......kOk..",
    ".kOOkkkkkkkkOOk.",
    "kOLOOOOOOOOOOLOk",
    "kddddddddddddddk",
    ".kddkkkkkkkkddk.",
    "..kdk......kdk..",
    "...k........k...",
    "................",
    "................",
    "................",
    "................",
  ],

  // ---- Paint window tools, 10×10, decorative ----
  toolSelect: [
    "k.k.k.k.k.",
    "..........",
    "k.......k.",
    "..........",
    "k.......k.",
    "..........",
    "k.......k.",
    "..........",
    "k.k.k.k.k.",
    "..........",
  ],
  toolPencil: [
    ".......kk.",
    "......kbbk",
    ".....kObk.",
    "....kOOk..",
    "...kOOk...",
    "..kOOk....",
    ".kdOk.....",
    ".kdk......",
    "kkk.......",
    "..........",
  ],
  toolPick: [
    "..kkkkk...",
    ".kGGGGGk..",
    "kGkkbkkGk.",
    "kk.kBk.kk.",
    "...kbk....",
    "...kBk....",
    "...kbk....",
    "...kBk....",
    "...kkk....",
    "..........",
  ],
  toolEllipse: [
    "..........",
    "...kkkk...",
    ".kk....kk.",
    "k........k",
    "k........k",
    "k........k",
    ".kk....kk.",
    "...kkkk...",
    "..........",
    "..........",
  ],
  toolRect: [
    "..........",
    "kkkkkkkkkk",
    "k........k",
    "k........k",
    "k........k",
    "k........k",
    "k........k",
    "k........k",
    "kkkkkkkkkk",
    "..........",
  ],
  toolText: [
    "....kk....",
    "...kkkk...",
    "...k..k...",
    "..kk..kk..",
    "..k....k..",
    ".kkkkkkkk.",
    ".k......k.",
    "kk......kk",
    "k........k",
    "..........",
  ],
  toolZoom: [
    "..kkkk....",
    ".kwGGGk...",
    "kwGGGGGk..",
    "kGGGGGGk..",
    "kGGGGGGk..",
    ".kGGGGk...",
    "..kkkkbk..",
    "......kbk.",
    ".......kbk",
    "........kk",
  ],
  toolPlus: [
    "..........",
    "....kk....",
    "....kk....",
    "....kk....",
    ".kkkkkkkk.",
    ".kkkkkkkk.",
    "....kk....",
    "....kk....",
    "....kk....",
    "..........",
  ],

  // ---- pause control, 8×8 ----
  pause: [
    "........",
    ".kk..kk.",
    ".kk..kk.",
    ".kk..kk.",
    ".kk..kk.",
    ".kk..kk.",
    ".kk..kk.",
    "........",
  ],
  play: [
    "........",
    ".k......",
    ".kk.....",
    ".kkk....",
    ".kkkk...",
    ".kkk....",
    ".kk.....",
    ".k......",
  ],
} as const satisfies Record<string, readonly string[]>;

export type PixelIconName = keyof typeof PIXEL_MAPS;

export type PixelMap = readonly string[];

/** Draws a map 1:1 into a 2D context (one map character = one canvas pixel). */
export function drawPixelMap(ctx: CanvasRenderingContext2D, map: PixelMap, palette: Record<string, string> = PIXEL_PALETTE) {
  ctx.clearRect(0, 0, ctx.canvas.width, ctx.canvas.height);
  map.forEach((row, y) => {
    for (let x = 0; x < row.length; x++) {
      const color = palette[row[x]];
      if (!color) continue;
      ctx.fillStyle = color;
      ctx.fillRect(x, y, 1, 1);
    }
  });
}

export const mapSize = (map: PixelMap) => ({ width: map[0]?.length ?? 0, height: map.length });

/** Ormine palette from the welcome video: Paint window swatches and illustrations. */
export const VIDEO_PALETTE = [
  "#110909",
  "#271616",
  "#431B0F",
  "#4B2C25",
  "#8F4822",
  "#B16830",
  "#E98D24",
  "#D8AA61",
  "#F5CC17",
  "#F4F76A",
] as const;
